// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// --------- //
// samplePin //
// --------- //

#define samplePin_wrap_target 0
#define samplePin_wrap 0
#define samplePin_pio_version 1

static const uint16_t samplePin_program_instructions[] = {
            //     .wrap_target
    0x4001, //  0: in     pins, 1
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program samplePin_program = {
    .instructions = samplePin_program_instructions,
    .length = 1,
    .origin = -1,
    .pio_version = samplePin_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config samplePin_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + samplePin_wrap_target, offset + samplePin_wrap);
    sm_config_set_in_pin_count(&c, 1);
    sm_config_set_in_shift(&c, 0, 1, 32);
    sm_config_set_fifo_join(&c, PIO_FIFO_JOIN_RX);
    return c;
}
#endif

